I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/tl/english/screens.rpy", line 34, in script
    old "Histórico"
Exception: A translation for "Histórico" already exists at game/tl/english/screens.rpy:7.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/tl/english/screens.rpy", line 34, in script
    old "Histórico"
  File "C:\Users\bruno\Documents\renpy-7.3.5-sdk\renpy\ast.py", line 2397, in execute
    renpy.translation.add_string_translation(self.language, self.old, self.new, newloc)
  File "C:\Users\bruno\Documents\renpy-7.3.5-sdk\renpy\translation\__init__.py", line 450, in add_string_translation
    stl.add(old, new, newloc)
  File "C:\Users\bruno\Documents\renpy-7.3.5-sdk\renpy\translation\__init__.py", line 388, in add
    quote_unicode(old), fn, line))
Exception: A translation for "Histórico" already exists at game/tl/english/screens.rpy:7.

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Piratas 1.0
Thu Jul 09 04:01:57 2020
